name: Testing Package
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  node-build:
    name: Building package for NodeJs and Bun
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: yarn config set enableImmutableInstalls false
      - run: yarn install
      - run: yarn build
      - run: node test/index.cjs
  browser-build:
    name: Building package for Browser
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: yarn config set enableImmutableInstalls false
      - run: yarn install
      - run: yarn add util
      - run: node ./generator/build_browser/index.js
      - run: yarn build
      - run: node test/index.cjs
  jsr-build:
    name: Building package for JSR
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - uses: denoland/setup-deno@v2
        with:
          deno-version: '2.x'
      - run: deno install
      - run: npx jsr publish --dry-run
      - run: deno run --allow-all test/index.ts
